### ISSUE TITLE
Connection is good, but never stops to write the bypass

### ISSUE THREAD

**Issue by utahcon** [Gilks/hostscan-bypass#12]
I am able to connect to the VPN through the mitm, but it never writes out the CSD script. Just continues to use the connection until I close it either through the client, or at the mitm.

Using AnyConnect 4.7 client. 

I was originally getting an error about the client not being installed, but that was fixed by changing the `--data-ascii` to `--data-binary` as noted in another issue.

**Comment by Gilks** [comment]
Are you sure your environment is using hostscan and not a posture module? Check out issue #7. I've wanted to support this but I don't have the environment for development at the moment.

**Comment by Gilks** [comment]
Closing due to lack of response.
