### ISSUE TITLE
Unable to connect into my server using AnyConnect

### ISSUE THREAD

**Issue by xephora** [Gilks/hostscan-bypass#16]
After using hostscan-bypass.go I am unable to connect using Cisco AnyConnect due to an unknown port error.

go run hostscan-bypass.go -l <AttackingIP> -p 443 -r https://<TargetIP>/CACHE/sdesktop/install/start.htm -s

[*] Listening for AnyConnect client connection..
[*] Accepted from: <MYIP>:<EphemeralPort>
dial tcp: address tcp///AttackingIP/CACHE/sdesktop/install/start.htm: unknown port

**Comment by Gilks** [comment]
That remote host does not look right to me. Did you try following the quick
start guide?

**Comment by xephora** [comment]
Sorry github removed my place holders. So based on the quick start guide i saw the following, if i try using the default command, it would accept the connection and timeout.

I tried the below as root and all timed out.

go run hostscan-bypass.go -l MYIP -p 443 -r TargetVPNIP:443 -s

go run hostscan-bypass.go -l MYIP -p 443 -r TargetIP:443 -s

go run hostscan-bypass.go -l MYIP -p 443 -r TargetIP/CACHE/sdesktop/install/start.htm:443 -s

go run hostscan-bypass.go -l MYIP -p 443 -r TargetIP:443/CACHE/sdesktop/install/start.htm -s

go run hostscan-bypass.go -l MYIP -p 443 -r TargetIP/CACHE/sdesktop/install/start.htm:443 -s

**Comment by Gilks** [comment]
The timeout comes from golang being unable to make a proper connection to
your target url. The best way to verify is by browsing there directly.

**Comment by Gilks** [comment]
No response. Closing.
