### ISSUE TITLE
How to forward the certificate validation request.

### ISSUE THREAD

**Issue by Aloento** [Gilks/hostscan-bypass#19]
In my case, access to the VPN server requires the use of a smart card for certificate authentication first. 
This proxy doesn't seem to forward this request, causing the VPN server to return a rejection.

**Comment by grouNDfx** [comment]
It looks like this was discussed some [here](https://github.com/Gilks/hostscan-bypass/pull/8#issuecomment-624632466). It's all a bit over my head, but hopefully can get you started :)
