### ISSUE TITLE
Does this issue have a CVE?

### ISSUE THREAD

**Issue by Frichetten** [Gilks/hostscan-bypass#2]
Great work man, this is interesting stuff. I just had a question, does this issue have an associated CVE? Or would this type of bypass even warrant a CVE from Cisco?

**Comment by Gilks** [comment]
I thought about submitting for a CVE but I didn't really think it warranted one. At the core of it, all you're doing is making a POST request to the AnyConnect server with the correct settings. The software is working as intended.

However, I'd be open to pursuing one if the community felt it was worthy of one.

**Comment by Frichetten** [comment]
Thats a good point, then again you are bypassing the expected behavior of the product and it's likely something they should fix. Again, great work dude. Made my day much more interesting!
