### ISSUE TITLE
RSA token with hostscan bypass

### ISSUE THREAD

**Issue by rlewkowicz** [Gilks/hostscan-bypass#5]
The UI only asks me for my password when using anyconnect via the bypass. My org also requires a rsa token. Any thoughts?

**Comment by rlewkowicz** [comment]
Ahh, so I actually have to connect to a url vs a standard domain. So remote.thing.com:443/place. I seem to be having trouble with this. Still investigating

**Comment by Gilks** [comment]
Are you getting any sort of error? It sounds like you're on the right track. The tool simply creates a MITM between your host and the VPN server. The kind of multi-factor auth being used doesn't matter to the tool.

**Comment by rlewkowicz** [comment]
I had to use the ip for the remote host, then set my hosts file to point at the local ip and then I was able to use the hostname and it worked as expected (although it didn't generate my csd, but I'll look into that)

Thank you for your time!
